### ISSUE TITLE
Burning PIC12LF1571 chip

### ISSUE THREAD

**Issue by Mind69** [danjperron/burnLVP#4]
Hello friend.

First of all, i wanna give you concratz for your job doing things like this python programs.

I have some error when i try burn PIC12LF1571 from my RP3-B+ GPIOs with external power-suplly (3V3).

I normaly burn it in windows with ICD3 (MPLAB-X) but i need do some tests with RASP and i need to burn it in same system, but i cant connect my programmer (ICD3) in my Rasp because they dont have drivers for it. So i see your "burnLVP" program and i think its a solution.

I try with "**burnLVPx.py**" and "**burnLVP.py**"
The error:

pi@raspberrypi:~/burnLVP/burnLVP $ sudo python burnLVPx.py ~/Desktop/FW-PIC/production.hex 
Raspberry Pi GPIO
File " /home/pi/Desktop/FW-PIC/production.hex " loaded
Scan CPU 
Check PIC12/16...
Cpu Id   = 0x0
Revision =  0x13
Unable to continue... Unable to handle this cpu
Cpu Id: 0x3040

pi@raspberrypi:~/burnLVP/burnLVP $ sudo python burnLVP.py ~/Desktop/FW-PIC/production.hex 
File " /home/pi/Desktop/FW-PIC/production.hex " loaded
LVP ON
Cpu : 0x3040  : Invalid
LVP OFF

Can you help me?

Many thanks.

**Comment by danjperron** [comment]
Hello Mind69,


 The pic12LF1571 is not in my table.


 I will have to fill the table  for it.

Maybe try to add this line in CpuPIC12.py



CpuList =  {  0x1b80 : ['PIC12F1840'  , 4096] ,
              0x3040 : ['PIC12LF1571' , 4096] ,


Not sure if it will work because the cpu ID for the pic12LF1571 is supposed to be 0x3053 and not 0x3040

Best way is to try it.

regards,

Daniel Perron

**Comment by Mind69** [comment]
With "burnLVPx.py":

File " /home/pi/Desktop/FW-PIC/production.hex " loaded
Scan CPU 
Check PIC12/16...
Cpu Id   = 0x0
Revision =  0x13
Found  PIC12LF1571 from Cpu Family  PIC12/16
Cpu Id: 0x3040  revision: 19
Bulk Erase Program , Data. .... done.
Program blank check................................Passed!
Data Blank check *** CPU eeprom data  at Address  0x0  =  0x0 Failed!

With "burnLVP.py":

File " /home/pi/Desktop/FW-PIC/production.hex " loaded
LVP ON
Cpu : 0x3040  : Invalid
LVP OFF


Can i try to edit to 0x3053? it suposted work?

>Thanks

**Comment by Mind69** [comment]
@danjperron 
Can i find some way to program this chip or is impossible with one Rasp?

**Comment by danjperron** [comment]
the program complain about eeprom datA

This chip doesn't have eeprom data  you should remark the data program  in 

burnLVPx.


CpuF.BulkErase()
if CpuF.ProgramBlankCheck():
#	  if CpuF.DataBlankCheck():
#	    CpuF.ProgramBurn(PicData)
    if CpuF.ProgramCheck(PicData):
#	       CpuF.DataBurn(PicData)
#	       if CpuF.DataCheck(PicData):
         CpuF.IDBurn(PicData)
         if CpuF.IDCheck(PicData):
           CpuF.ConfigBurn(PicData)
           if CpuF.ConfigCheck(PicData):
             print "Program verification passed!" 


Please adjust indentation.

regards,
Daniel

**Comment by danjperron** [comment]
oops typo from the last mail



CpuF.BulkErase()
if CpuF.ProgramBlankCheck():
    CpuF.ProgramBurn(PicData)
    if CpuF.ProgramCheck(PicData):
         CpuF.IDBurn(PicData)
         if CpuF.IDCheck(PicData):
           CpuF.ConfigBurn(PicData)
           if CpuF.ConfigCheck(PicData):


Daniel

**Comment by Mind69** [comment]
Raspberry Pi GPIO
File " /home/pi/Desktop/FW-PIC/production.hex " loaded
Scan CPU 
Check PIC12/16...
Cpu Id   = 0x0
Revision =  0x13
Found  PIC12LF1571 from Cpu Family  PIC12/16
Cpu Id: 0x3040  revision: 19
Bulk Erase Program , Data. .... done.
Program blank check................................Passed!
Writing Program................................Done.
Program check ................................Passed!
Writing Config..Done.
Config Check..Passed!
Program verification passed!


Daniel you make my day, my week, my everything...

Big hug from Portugal, i hope you have safe from this pandemic virus!
Thank you very mutch, really, i dont have words.

**Comment by danjperron** [comment]
Glad that I was able to help you.

I was in Portugal visiting Lisbonne and Porto last summer.

Have a nice one.

Daniel

**Comment by Mind69** [comment]
Ho really, i hope you enjoyed this summer vacations.

Thanks again and continue with this fantastic work that you have to shared us.
